# Generated by Django 3.1.7 on 2021-02-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainuserdata', '0006_mlmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLModel',
        ),
    ]
