# Generated by Django 3.1.7 on 2021-02-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainuserdata', '0008_mlmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
