# Generated by Django 3.1.7 on 2021-02-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainuserdata', '0009_auto_20210226_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlmodel',
            old_name='model_path',
            new_name='model_async_id',
        ),
    ]
